version: "3.8"
services:
  demodb:
    image: postgres:13
    platform: linux/amd64
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
    ports:
      - 5432:5432
    networks:
      - demo
networks:
  demo:
